In [1]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame

In [4]:
import webbrowser
website = 'http://en.wikipedia.org/wiki/NFL_win-loss_records'
webbrowser.open(website)

True

In [21]:
nfl_frame = pd.read_clipboard(sep="\t")

In [22]:
nfl_frame

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference
0,1,Green Bay Packers,751,567,37,0.568,1921,1355,NFC North
1,2,Chicago Bears,758,573,42,0.567,1920,1373,NFC North
2,3,Dallas Cowboys,514,392,6,0.567,1960,912,NFC East
3,4,Miami Dolphins,449,355,4,0.558,1966,808,AFC East
4,5,New England Patriots,490,399,9,0.551,1960,898,AFC East
5,6,Baltimore Ravens,187,154,1,0.548,1996,342,AFC North
6,7,San Francisco 49ers,550,455,14,0.547,1950,1019,NFC West
7,8,New York Giants,697,591,33,0.540,1925,1321,NFC East
8,9,Denver Broncos,476,404,10,0.540,1960,890,AFC West
9,10,Minnesota Vikings,468,406,10,0.535,1961,884,NFC North
10,11,Indianapolis Colts,516,456,7,0.531,1953,979,AFC South
11,12,Oakland Raiders,469,415,11,0.530,1960,895,AFC West
12,13,Pittsburgh Steelers,628,567,21,0.525,1933,1216,AFC North
13,14,Kansas City Chiefs,443,420,12,0.513,1960,875,AFC West
14,15,Washington Redskins,601,583,27,0.507,1932,1211,NFC East
15,16,Seattle Seahawks,329,326,0,0.502,1976,655,NFC West
16,17,Cleveland Browns,472,471,10,0.501,1950,953,AFC North
17,18,St. Louis Rams,559,564,21,0.498,1937,1144,NFC West
18,19,San Diego Chargers,432,437,11,0.497,1960,880,AFC West
19,20,Carolina Panthers,173,175,1,0.497,1995,349,NFC South
20,21,Philadelphia Eagles,567,603,26,0.485,1933,1196,NFC East
21,22,Tennessee Titans,418,461,6,0.476,1960,885,AFC South
22,23,Buffalo Bills,407,466,8,0.467,1960,881,AFC East
23,24,New York Jets,399,470,8,0.460,1960,877,AFC East
24,25,Detroit Lions,542,646,32,0.457,1930,1220,NFC North
25,26,Jacksonville Jaguars,157,188,0,0.455,1995,345,AFC South
26,27,Cincinnati Bengals,343,412,3,0.454,1968,758,AFC North
27,28,New Orleans Saints,338,427,5,0.442,1967,770,NFC South
28,29,Houston Texans,99,129,0,0.434,2002,228,AFC South
29,30,Atlanta Falcons,337,444,6,0.432,1966,787,NFC South
30,31,Arizona Cardinals,541,732,39,0.427,1920,1312,NFC West
31,32,Tampa Bay Buccaneers,247,395,1,0.385,1976,643,NFC South

In [13]:
nfl_frame.columns

Index([u'Rank', u'Team', u'Won', u'Lost', u'Tied*', u'Pct.', u'First',
       u'Season', u'Total', u'Games', u'Conference'],
      dtype='object')

In [23]:
nfl_frame.Rank

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
Name: Rank, dtype: int64

In [24]:
nfl_frame['First Season']

0     1921
1     1920
2     1960
3     1966
4     1960
5     1996
6     1950
7     1925
8     1960
9     1961
10    1953
11    1960
12    1933
13    1960
14    1932
15    1976
16    1950
17    1937
18    1960
19    1995
20    1933
21    1960
22    1960
23    1960
24    1930
25    1995
26    1968
27    1967
28    2002
29    1966
30    1920
31    1976
Name: First Season, dtype: int64

In [28]:
DataFrame(nfl_frame, columns=['Team', 'First Season', 'Total Games', 'Owner'])

                    Team  First Season  Total Games  Owner
0      Green Bay Packers          1921         1355    NaN
1          Chicago Bears          1920         1373    NaN
2         Dallas Cowboys          1960          912    NaN
3         Miami Dolphins          1966          808    NaN
4   New England Patriots          1960          898    NaN
5       Baltimore Ravens          1996          342    NaN
6    San Francisco 49ers          1950         1019    NaN
7        New York Giants          1925         1321    NaN
8         Denver Broncos          1960          890    NaN
9      Minnesota Vikings          1961          884    NaN
10    Indianapolis Colts          1953          979    NaN
11       Oakland Raiders          1960          895    NaN
12   Pittsburgh Steelers          1933         1216    NaN
13    Kansas City Chiefs          1960          875    NaN
14   Washington Redskins          1932         1211    NaN
15      Seattle Seahawks          1976          655    NaN
16      Cleveland Browns          1950          953    NaN
17        St. Louis Rams          1937         1144    NaN
18    San Diego Chargers          1960          880    NaN
19     Carolina Panthers          1995          349    NaN
20   Philadelphia Eagles          1933         1196    NaN
21      Tennessee Titans          1960          885    NaN
22         Buffalo Bills          1960          881    NaN
23         New York Jets          1960          877    NaN
24         Detroit Lions          1930         1220    NaN
25  Jacksonville Jaguars          1995          345    NaN
26    Cincinnati Bengals          1968          758    NaN
27    New Orleans Saints          1967          770    NaN
28        Houston Texans          2002          228    NaN
29       Atlanta Falcons          1966          787    NaN
30     Arizona Cardinals          1920         1312    NaN
31  Tampa Bay Buccaneers          1976          643    NaN

In [31]:
nfl_frame.head()

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference
0,1,Green Bay Packers,751,567,37,0.568,1921,1355,NFC North
1,2,Chicago Bears,758,573,42,0.567,1920,1373,NFC North
2,3,Dallas Cowboys,514,392,6,0.567,1960,912,NFC East
3,4,Miami Dolphins,449,355,4,0.558,1966,808,AFC East
4,5,New England Patriots,490,399,9,0.551,1960,898,AFC East

In [32]:
nfl_frame.head(10)

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference
0,1,Green Bay Packers,751,567,37,0.568,1921,1355,NFC North
1,2,Chicago Bears,758,573,42,0.567,1920,1373,NFC North
2,3,Dallas Cowboys,514,392,6,0.567,1960,912,NFC East
3,4,Miami Dolphins,449,355,4,0.558,1966,808,AFC East
4,5,New England Patriots,490,399,9,0.551,1960,898,AFC East
5,6,Baltimore Ravens,187,154,1,0.548,1996,342,AFC North
6,7,San Francisco 49ers,550,455,14,0.547,1950,1019,NFC West
7,8,New York Giants,697,591,33,0.540,1925,1321,NFC East
8,9,Denver Broncos,476,404,10,0.540,1960,890,AFC West
9,10,Minnesota Vikings,468,406,10,0.535,1961,884,NFC North

In [33]:
nfl_frame.tail(10)

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference
22,23,Buffalo Bills,407,466,8,0.467,1960,881,AFC East
23,24,New York Jets,399,470,8,0.460,1960,877,AFC East
24,25,Detroit Lions,542,646,32,0.457,1930,1220,NFC North
25,26,Jacksonville Jaguars,157,188,0,0.455,1995,345,AFC South
26,27,Cincinnati Bengals,343,412,3,0.454,1968,758,AFC North
27,28,New Orleans Saints,338,427,5,0.442,1967,770,NFC South
28,29,Houston Texans,99,129,0,0.434,2002,228,AFC South
29,30,Atlanta Falcons,337,444,6,0.432,1966,787,NFC South
30,31,Arizona Cardinals,541,732,39,0.427,1920,1312,NFC West
31,32,Tampa Bay Buccaneers,247,395,1,0.385,1976,643,NFC South

In [35]:
nfl_frame.ix[3]

Rank                         4
Team            Miami Dolphins
Won                        449
Lost                       355
Tied*                        4
Pct.                     0.558
First Season              1966
Total Games                808
Conference            AFC East
Name: 3, dtype: object